services: #criar serviços em container
  backend: #serviço chamado backend
    image: semana6:latest #imagem local
    restart: always #sempre que rodar o docker-compose ele vai dar restar nesse container
    ports: #port-foward 3333(máquina) -> 3333(docker)
      - 3333:3333
    environment:
      - DB_HOST=db #banco de dados que eu estou acessando
    networks:
      - spring-postgres #rede interna do docker que esse service faz parte
  db:
    image: postgres
    restart: always
    volumes: #volume de dados que o docker vai usar
      - db-data:/var/lib/postgresql/data #C:var
    networks: 
      - spring-postgres
    environment:
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  db-data:
networks:
  spring-postgres: